### ISSUE TITLE
Sublime Text 3 Support

### ISSUE THREAD

**Issue by schickling** [bradfeehan/SublimePHPCoverage#11]
Thanks for the plugin so far.

Will you implement support for the new Sublime Text 3?

**Comment by bradfeehan** [comment]
I'll take a look at it. I'm not currently using Sublime Text 3, basically because of this reason (plugins need to be updated to work). Have most of the plugins you use been updated already?

**Comment by schickling** [comment]
Yes, almost all Plugins I use already work in ST3 again.

**Comment by hd-deman** [comment]
+1 for ST3, and yes most useful plugins updated.

**Comment by stevenklar** [comment]
At the moment this plugin "works" in ST3.
But when you save the file its incredibly slow (maybe because there need to be done some work to implement the new api?).

Works yes, but not as good as in ST2.

Looking forward to wait for your ST3 solution. Otherwise if I have time would maybe send you an pull request.

**Comment by bradfeehan** [comment]
I'm currently working on this, will update soon with progress.

**Comment by stevenklar** [comment]
Cool! :+1:
