### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by briandela** [bradfeehan/SublimePHPCoverage#22]
I'd like to modify/fork this to work for JavaScript too - I'm using lab (https://github.com/hapijs/lab) to run my tests and it outputs a clover coverage file. 

Just wondering for some pointers as to where the PHP specific side of things are.

Thanks.

**Comment by bradfeehan** [comment]
It's been a while since I wrote this code. Honestly, I don't actually know!

I looked through the code, and from what I can see there's very little PHP-specific details. Maybe the project should be called "Clover coverage" or similar, since that's the format of the coverage data output by PHPUnit...

If you can get a JavaScript testing tool that outputs Clover coverage data, as you say, I can't see what would prevent it from working out-of-the-box. But my need for this plugin has all but disappeared since writing it, and I have even less need for the same for JavaScript...

But do let me know about any errors you encounter, I'll see if I can help troubleshoot.
